apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helmproj.fullname" . }}
  labels:
    {{- include "helmproj.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "helmproj.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helmproj.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helmproj.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: squid
              containerPort: {{ .Values.service.internalPort | default "3128" }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          {{- if .Values.volumeMounts }}
          {{- if or .Values.volumeMounts.configmaps .Values.volumeMounts.secrets }}
          volumeMounts:
            {{- range $key, $val := .Values.volumeMounts.configmaps }}
            - name: configs
              mountPath: {{ $.Values.volumeMountsPath.configmaps }}/{{ $key }}
              subPath: {{ $key }}
              readOnly: true
            {{- end }}
            {{- range $key, $val := .Values.volumeMounts.secrets }}
            - name: secrets
              mountPath: {{ $.Values.volumeMountsPath.secrets }}/{{ $key }}
              subPath: {{ $key }}
              readOnly: true
            {{- end }}
          {{- end }}
          {{- end }}
          {{- if .Values.envFrom }}
          {{- if or .Values.envFrom.configmaps .Values.envFrom.secrets }}
          envFrom:
            {{- if .Values.envFrom.configmaps }}
            - configMapRef:
                name: {{ template "helmproj.fullname" . }}
            {{- end }}
            {{- if .Values.envFrom.secrets }}
            - secretRef:
                name: {{ template "helmproj.fullname" . }}
            {{- end }}
          {{- end }}
          {{- end }}
          {{- with .Values.env }}
          env:
            {{- range $k, $v := . }}
            - name: {{ $k | quote}}
              value: {{ $v | quote }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if or .Values.volumeMounts.configmaps .Values.volumeMounts.secrets }}
      volumes:
        {{- if .Values.volumeMounts.configmaps }}
        - name: configs
          configMap:
            name: {{ template "helmproj.fullname" . }}-vols
        {{- end }}
        {{- if .Values.volumeMounts.secrets }}
        - name: secrets
          secret:
            secretName: {{ template "helmproj.fullname" . }}-vols
        {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
