apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashy
  labels:
    app: dashy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashy
  template:
    metadata:
      labels:
        app: dashy
    spec:
      containers:
      - name: dashy
        image: lissy93/dashy:2.1.1
        ports:
          - containerPort: 80
        volumeMounts:
          - name: config
            mountPath: /app/public
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: dashy

