---
# Deploys a new MinIO Pod into the metadata.namespace Kubernetes namespace
#
# The `spec.containers[0].args` contains the command run on the pod
# The `/data` directory corresponds to the `spec.containers[0].volumeMounts[0].mountPath`
# That mount path corresponds to a Kubernetes HostPath which binds `/data` to a local drive or volume on the worker node where the pod runs
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "helmproj.fullname" . }}
  labels:
    v1.min.io/tenant: {{ .Values.tenant | default "minio" | quote }}
    app: {{ template "helmproj.name" . }}
    chart: {{ template "helmproj.chart" . }}
    draft: {{ .Values.draft | default "draft-app" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      v1.min.io/tenant: {{ .Values.tenant | default "minio" | quote }}
  template:
    metadata:
      labels:
        v1.min.io/tenant: {{ .Values.tenant | default "minio" | quote }}
        app: {{ template "helmproj.name" . }}
        draft: {{ .Values.draft | default "draft-app" }}
        release: {{ .Release.Name }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /bin/bash
        - -c
        args: 
        - minio server /data --console-address :9090
        envFrom:
          - configMapRef:
              name: {{ template "helmproj.fullname" . }}-configmap
          - secretRef:
              name: {{ template "helmproj.fullname" . }}-secret
        volumeMounts:
        - mountPath: /data
          name: {{ template "helmproj.fullname" . }}-data
        resources: {{- toYaml .Values.resources | nindent 10 }}

      volumes:
      - name: {{ template "helmproj.fullname" . }}-data
        persistentVolumeClaim:
          claimName: {{ template "helmproj.fullname" . }}-data

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | indent 2 }}
      {{- end }}
      
      {{- with .Values.affinity }}
      affinity:
        {{ toYaml . | indent 2 }}
      {{- end }}
      
      {{- with .Values.tolerations }}
      tolerations:
        {{ toYaml . | indent 8 }}
      {{- end }}
