apiVersion: v1
kind: Service
metadata:
  name: console
  labels:
    v1.min.io/tenant: {{ .Values.tenant | default "minio" | quote }}
    app: {{ template "helmproj.name" . }}
    chart: {{ template "helmproj.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- if .Values.service.console.annotations }}
  annotations: {{- toYaml .Values.service.console.annotations | nindent 4 }}
  {{- end }}
spec:
  ports:
  - name: console
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    v1.min.io/tenant: {{ .Values.tenant | default "minio" | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    v1.min.io/tenant: {{ .Values.tenant | default "minio" | quote }}
    app: {{ template "helmproj.name" . }}
    chart: {{ template "helmproj.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- if .Values.service.api.annotations }}
  annotations: {{- toYaml .Values.service.api.annotations | nindent 4 }}
  {{- end }}
spec:
  ports:
  - name: api
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    v1.min.io/tenant: {{ .Values.tenant | default "minio" | quote }}
  type: ClusterIP
